# Generated by Django 4.2.1 on 2023-07-15 10:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('fullName', models.CharField(blank=True, default='', max_length=50)),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='nonregistredCustomer',
            fields=[
                ('fullName', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('subCategory', models.CharField(blank=True, max_length=200, null=True)),
                ('productType', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('boys', 'boys'), ('girls', 'girls'), ('men', 'men'), ('women', 'women')], default='boys', max_length=20)),
                ('category', models.CharField(choices=[('footwear', 'footwear'), ('apparel', 'apparel')], default='apparel', max_length=20)),
                ('colour', models.CharField(blank=True, max_length=200, null=True)),
                ('usage', models.CharField(blank=True, max_length=400, null=True)),
                ('productTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('productImage', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='products/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageUrl', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['-colour'],
            },
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='NonRegistredOrder',
            fields=[
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nonRegistredCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.nonregistredcustomer')),
            ],
        ),
        migrations.AddField(
            model_name='nonregistredcustomer',
            name='cart',
            field=models.ManyToManyField(blank=True, to='store.productset'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, to='store.productset'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
