# Generated by Django 4.2.1 on 2023-07-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_address_order_phonenumber_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='temporaryToken',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
