# Generated by Django 4.2.1 on 2023-08-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ownerName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
