# Generated by Django 4.2.1 on 2023-09-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_customer_user_alter_productset_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='binarySim',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
