# Generated by Django 4.2.1 on 2023-09-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_binarysim'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mostSimilar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
