# Generated by Django 4.2.1 on 2023-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_binarysim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='binarySim',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
